name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '!.github/workflows/**'
      - '.github/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: CI with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
